cask "groqtalk" do
  # Development reference only. The public tap cask is generated by
  # .github/scripts/update-homebrew-cask.sh with a versioned sha256 after the
  # release DMG exists.
  version "1.12.0"
  sha256 :no_check

  url "https://github.com/mean-weasel/groqtalk/releases/download/v#{version}/GroqTalk-#{version}-macos.dmg"
  name "GroqTalk"
  desc "Menu bar speech-to-text transcription"
  homepage "https://github.com/mean-weasel/groqtalk"

  auto_updates true
  depends_on macos: ">= :sonoma"

  app "GroqTalk.app"

  zap trash: [
    "~/Library/Application Support/com.neonwatty.GroqTalk",
    "~/Library/Preferences/com.neonwatty.GroqTalk.plist",
    "~/Library/Caches/com.neonwatty.GroqTalk",
  ]
end
